sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: GPLv3
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/slaytostay/slaytostay.github.io"

repository: slaytostay/slaytostay.github.io

title: Slay to Stay
description: Progress Log

include: [_data, assets]
exclude: [README.md, LICENSE, tools]
